// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pkjigvacvddcnlxhvvba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBramlndmFjdmRkY25seGh2dmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjkzNDIsImV4cCI6MjA3NjcwNTM0Mn0.7OVF6Dbe6ByyU0rVDUXOHwUD3ZgkoQUI-7DxVDr5K8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);